- name: Asegurar que Node esté instalado
  apt:
    name: nodejs
    state: present
    update_cache: yes
- name: Asegurar que NPM esté instalado
  apt:
    name: npm
    state: present
    update_cache: yes    
- name: Crear usuario del servicio
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    state: present
- name: Crear directorio de la aplicación
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
- name: Copiar la carpeta dist de la aplicación
  copy:
    src: .
    dest: "{{ app_dir }}/"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
- name: Copiar el servicio systemd
  template:
    src: nestjs.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
  notify:
    - Reiniciar servicio Spring Boot
- name: Habilitar e iniciar el servicio
  systemd:
    name: "{{ service_name }}"
    enabled: yes
    state: started